### ISSUE TITLE
sotawhat.py script need to import warnings

### ISSUE THREAD

**Issue by aplamhden22** [chiphuyen/sotawhat#22]
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\pychat\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\pychat\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Anaconda3\envs\Pychat\Scripts\sotawhat.exe\__main__.py", line 9, in <module>
  File "c:\users\user\anaconda3\envs\pychat\lib\site-packages\sotawhat\sotawhat.py", line 281, in main
    warnings.warn('On Windows, encoding errors may arise when displaying the data.\n'
**NameError: name 'warnings' is not defined**

**Comment by aplamhden22** [comment]
import warnings for line 282 #21
